//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppDiplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResults
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResults()
        {
            this.UserAnswers = new HashSet<UserAnswers>();
        }
    
        public int ResultID { get; set; }
        public int UserID { get; set; }
        public int TestID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public Nullable<double> PercentageScore { get; set; }
        public Nullable<bool> IsPassed { get; set; }
    
        public virtual Tests Tests { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswers> UserAnswers { get; set; }
    }
}
