//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppDiplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestGroups
    {
        public int TestGroupID { get; set; }
        public int TestID { get; set; }
        public int GroupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
