//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppDiplom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswers
    {
        public int UserAnswerID { get; set; }
        public int ResultID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual TestResults TestResults { get; set; }
    }
}
